import * as THREE from './vendor/three.module.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';

const $=s=>document.querySelector(s), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const defs=[
 {name:'雷咒师',role:'法师',icon:'⚡',color:0x58cfff,hp:760,atk:76,range:8.4,speed:7.1,skills:['雷链','霆狱','九霄天罚'],desc:'连锁闪电、范围雷狱与全场天罚'},
 {name:'玄甲卫',role:'坦克',icon:'🛡️',color:0xe2bd78,hp:1320,atk:48,range:2.2,speed:5.7,skills:['镇岳击','玄甲阵','山河震'],desc:'重甲控制、团队护盾和群体震飞'},
 {name:'夜行刃',role:'刺客',icon:'🗡️',color:0xc681ff,hp:790,atk:96,range:2.1,speed:8.2,skills:['影袭','无形步','瞬狱杀'],desc:'高速突进、隐身和残血斩杀'},
 {name:'星弦',role:'射手',icon:'🏹',color:0x72edbc,hp:720,atk:82,range:9.2,speed:7.4,skills:['穿云矢','逐星步','群星坠'],desc:'穿透箭、机动强化和持续箭雨'},
 {name:'青灯使',role:'辅助',icon:'🏮',color:0xa7ff8e,hp:870,atk:55,range:7.2,speed:6.8,skills:['引魂灯','回春渡','彼岸华光'],desc:'弹射法术、群体治疗和团队结界'},
 {name:'炎武尊',role:'战士',icon:'🔥',color:0xff7b53,hp:1040,atk:72,range:2.4,speed:6.6,skills:['焚拳','浴火身','炎神降世'],desc:'近战吸血、持续强化和狂暴变身'}
];
let scene,camera,renderer,clock,raycaster,ground,game=null,templates=[],animations=[],loaded=0,fpsFrames=0,fpsTime=0,selectedHero=0,preview=null;
const loader=new GLTFLoader(), mixers=[], keys={}, joy={x:0,y:0,id:null};
let room={mode:'solo',code:'',channel:null,host:false,peer:false,ready:false};
window.addEventListener('error',e=>showError(e.message));window.addEventListener('unhandledrejection',e=>showError(e.reason?.message||String(e.reason)));
function showError(t){$('#error').style.display='block';$('#error').textContent='运行错误：'+t}

initRenderer();loadAssets();
function initRenderer(){scene=new THREE.Scene();scene.background=new THREE.Color(0x07121c);scene.fog=new THREE.FogExp2(0x132331,.012);camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,250);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;document.body.prepend(renderer.domElement);clock=new THREE.Clock();raycaster=new THREE.Raycaster();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})}
function loadAssets(){for(let i=0;i<6;i++)loader.load(`./models/hero-${i}.glb`,g=>{g.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});templates[i]=g.scene;animations[i]=g.animations;assetDone()},undefined,e=>{showError(`英雄${i+1}模型加载失败`);console.error(e)})}
function assetDone(){loaded++;$('#progress').style.width=(loaded/6*100)+'%';$('#loadText').textContent=`已唤醒 ${loaded}/6 位英雄`;if(loaded===6){setTimeout(()=>{$('#loading').classList.add('hidden');buildCards();$('#select').classList.remove('hidden');initHeroPreview()},250)}}
function buildCards(){initRoomLobby();const box=$('#cards');box.innerHTML='';defs.forEach((d,i)=>{let b=document.createElement('button');b.className='card'+(i===selectedHero?' selected':'');b.dataset.hero=i;b.innerHTML=`<div class="portrait" style="color:#${d.color.toString(16).padStart(6,'0')}">${d.icon}</div><small>${d.role}</small><strong>${d.name}</strong><p>${d.desc}</p><em>${d.skills.join(' · ')}</em>`;b.onclick=()=>selectHeroPreview(i);b.onpointerenter=()=>{if(matchMedia('(hover:hover)').matches)selectHeroPreview(i)};box.appendChild(b)});$('#enterBattle').onclick=()=>startSelected()}
function startSelected(){if(room.mode==='online'){if(!room.channel||!room.peer){setRoomStatus('请先创建或加入房间，并等待队友加入');return}room.ready=true;room.channel.postMessage({type:'ready',hero:selectedHero});syncRoom();if(!room.host){setRoomStatus('已准备，等待房主开局');return}room.channel.postMessage({type:'start',hero:selectedHero});}start(selectedHero)}
function roomCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function setRoomStatus(text){const el=$('#roomStatus');if(el)el.textContent=text}
function closeRoom(){if(room.channel)room.channel.close();room={mode:room.mode,code:'',channel:null,host:false,peer:false,ready:false}}
function syncRoom(){const b=$('#readyRoom');if(!b)return;b.disabled=!room.peer||room.ready;b.textContent=room.ready?'已准备':'准备开局';if(room.mode==='online'&&room.peer&&!room.ready)setRoomStatus(room.host?'队友已加入，选择英雄后开始':'已进入房间，选择英雄并准备')}
function openRoom(code,host){closeRoom();room.code=code;room.host=host;room.channel=new BroadcastChannel('arena-3d-room-'+code);room.channel.onmessage=e=>{const m=e.data;if(!m||m.type==='hello')return;if(m.type==='join'){room.peer=true;room.channel.postMessage({type:'presence'});syncRoom()}if(m.type==='presence'){room.peer=true;syncRoom()}if(m.type==='ready'){room.peer=true;setRoomStatus(`队友已锁定 ${defs[m.hero]?.name||'英雄'}`);syncRoom()}if(m.type==='start'&&!room.host){setRoomStatus('房主已开局，进入战场');start(selectedHero)}};room.channel.postMessage({type:'join'});setRoomStatus(host?`房间 ${code} 已创建，等待队友`:`已加入房间 ${code}，正在呼叫房主`);syncRoom()}
function initRoomLobby(){if($('#roomPanel').dataset.bound)return;$('#roomPanel').dataset.bound='1';document.querySelectorAll('.mode-tab').forEach(b=>b.onclick=()=>{room.mode=b.dataset.mode;document.querySelectorAll('.mode-tab').forEach(x=>x.classList.toggle('active',x===b));$('#roomPanel').classList.toggle('open',room.mode==='online');if(room.mode==='solo')closeRoom();else setRoomStatus('创建房间，或输入房间码加入')});$('#createRoom').onclick=()=>{let code=roomCode();$('#roomCode').value=code;openRoom(code,true)};$('#joinRoom').onclick=()=>{let code=$('#roomCode').value.trim().toUpperCase();if(!/^[A-Z0-9]{4,6}$/.test(code)){setRoomStatus('请输入 4–6 位字母或数字房间码');return}openRoom(code,false)};$('#readyRoom').onclick=()=>startSelected()}

function cloneSkinnedModel(source){const sourceLookup=new Map(),cloneLookup=new Map(),clone=source.clone(true);parallelTraverse(source,clone,(a,b)=>{sourceLookup.set(b,a);cloneLookup.set(a,b)});clone.traverse(node=>{if(!node.isSkinnedMesh)return;const sourceMesh=sourceLookup.get(node);node.skeleton=sourceMesh.skeleton.clone();node.bindMatrix.copy(sourceMesh.bindMatrix);node.skeleton.bones=sourceMesh.skeleton.bones.map(bone=>cloneLookup.get(bone));node.bind(node.skeleton,node.bindMatrix)});return clone}
function parallelTraverse(a,b,callback){callback(a,b);for(let i=0;i<a.children.length;i++)parallelTraverse(a.children[i],b.children[i],callback)}
function initHeroPreview(){const host=$('#heroPreview'),pScene=new THREE.Scene(),pCamera=new THREE.PerspectiveCamera(32,1,.05,100),pRenderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'}),heroRoot=new THREE.Group();pRenderer.setPixelRatio(Math.min(devicePixelRatio,1.6));pRenderer.outputColorSpace=THREE.SRGBColorSpace;pRenderer.toneMapping=THREE.ACESFilmicToneMapping;pRenderer.toneMappingExposure=1.18;pRenderer.shadowMap.enabled=true;host.appendChild(pRenderer.domElement);pScene.add(new THREE.HemisphereLight(0xb9dcff,0x172034,2.2));let key=new THREE.DirectionalLight(0xffdfb5,4.3);key.position.set(-3,7,5);key.castShadow=true;pScene.add(key);let rim=new THREE.DirectionalLight(0x59bfff,3.2);rim.position.set(4,4,-4);pScene.add(rim);let floor=new THREE.Mesh(new THREE.CircleGeometry(3.5,48),new THREE.MeshStandardMaterial({color:0x172a3f,metalness:.22,roughness:.58}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;pScene.add(floor,heroRoot);pCamera.position.set(0,2.7,8);pCamera.lookAt(0,2.15,0);const resize=()=>{let r=host.getBoundingClientRect(),w=Math.max(1,r.width),h=Math.max(1,r.height);pRenderer.setSize(w,h,false);pCamera.aspect=w/h;pCamera.updateProjectionMatrix()};let dragging=false,lastX=0;const down=e=>{dragging=true;lastX=e.clientX;pRenderer.domElement.setPointerCapture?.(e.pointerId)},move=e=>{if(!dragging)return;heroRoot.rotation.y+=(e.clientX-lastX)*.012;lastX=e.clientX},up=()=>dragging=false;pRenderer.domElement.addEventListener('pointerdown',down);pRenderer.domElement.addEventListener('pointermove',move);pRenderer.domElement.addEventListener('pointerup',up);pRenderer.domElement.addEventListener('pointercancel',up);let observer=new ResizeObserver(resize);observer.observe(host);preview={scene:pScene,camera:pCamera,renderer:pRenderer,root:heroRoot,mixer:null,model:null,active:true,last:performance.now(),observer};resize();selectHeroPreview(selectedHero);requestAnimationFrame(previewLoop)}
function selectHeroPreview(id){selectedHero=id;document.querySelectorAll('.card').forEach((card,i)=>card.classList.toggle('selected',i===id));$('#previewRole').textContent=`${defs[id].role} · ${defs[id].skills.join(' / ')}`;$('#previewName').textContent=defs[id].name;$('#previewDesc').textContent=defs[id].desc+' · 拖动旋转';if(!preview)return;if(preview.mixer){preview.mixer.stopAllAction();preview.mixer.uncacheRoot(preview.model)}if(preview.model)preview.root.remove(preview.model);let model=cloneSkinnedModel(templates[id]);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});let box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),scale=4.35/Math.max(size.y,.001);model.scale.setScalar(scale);box.setFromObject(model);let center=box.getCenter(new THREE.Vector3());model.position.set(-center.x,-box.min.y,-center.z);preview.root.add(model);preview.root.rotation.y=.25;preview.model=model;preview.mixer=new THREE.AnimationMixer(model);let clip=animations[id].find(a=>a.name.toLowerCase()==='idle')||animations[id].find(a=>a.name.toLowerCase().includes('idle'))||animations[id][0];if(clip)preview.mixer.clipAction(clip).play()}
function previewLoop(now){if(!preview?.active)return;let dt=Math.min(.05,(now-preview.last)/1000);preview.last=now;preview.mixer?.update(dt);preview.root.rotation.y+=dt*.18;preview.renderer.render(preview.scene,preview.camera);requestAnimationFrame(previewLoop)}
function stopHeroPreview(){if(!preview)return;preview.active=false;preview.observer.disconnect();preview.mixer?.stopAllAction();preview.renderer.dispose();preview.renderer.domElement.remove();preview=null}

function start(pick){stopHeroPreview();$('#select').classList.add('hidden');$('#hud').classList.remove('hidden');buildWorld();const rest=[0,1,2,3,4,5].filter(i=>i!==pick),order=[pick,...rest];game={time:0,last:performance.now(),heroes:[],minions:[],shots:[],zones:[],structures:[],effects:[],blueKills:0,redKills:0,wave:1,over:false,player:null,utility:{recall:0,heal:0,flash:0}};order.slice(0,3).forEach((id,i)=>spawnHero(id,0,new THREE.Vector3(-48+i*1.8,0,-5+i*5),i===0));order.slice(3).forEach((id,i)=>spawnHero(id,1,new THREE.Vector3(48-i*1.8,0,-5+i*5)));spawnStructures();buildTeamStrip();initShopUI();updateGold();document.querySelectorAll('.shopItem').forEach(b=>b.classList.remove('owned'));feed('战斗开始：摧毁敌方诸界核心！',0xffdc80);clock.start();requestAnimationFrame(loop)}
function buildTeamStrip(){let box=$('#teamStrip');box.innerHTML='';for(const h of game.heroes){let face=document.createElement('div');face.className='team-face'+(h.team?' enemy':'');face.textContent=h.def.icon;face.title=`${h.team?'赤渊':'苍穹'} · ${h.def.name}`;box.appendChild(face)}}
function buildWorld(){scene.clear();mixers.length=0;scene.background=new THREE.Color(0x0a1923);scene.fog=new THREE.FogExp2(0x0f232c,.011);scene.add(new THREE.HemisphereLight(0x9cc8f2,0x1c2810,1.1));let sun=new THREE.DirectionalLight(0xffdca8,2.6);sun.position.set(-25,48,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-70;sun.shadow.camera.right=70;sun.shadow.camera.top=45;sun.shadow.camera.bottom=-45;scene.add(sun);
 const tex=new THREE.CanvasTexture(makeGroundTexture());tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(14,7);ground=new THREE.Mesh(new THREE.PlaneGeometry(130,66),new THREE.MeshStandardMaterial({map:tex,roughness:.95,metalness:.02}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);let laneTex=stoneTexture().clone();laneTex.needsUpdate=true;laneTex.repeat.set(20,2.6);let lane=new THREE.Mesh(new THREE.PlaneGeometry(120,16),new THREE.MeshStandardMaterial({map:laneTex,color:0x757c85,roughness:.92}));lane.rotation.x=-Math.PI/2;lane.position.y=.015;lane.receiveShadow=true;scene.add(lane);for(let x=-52;x<=52;x+=8){let slab=new THREE.Mesh(new THREE.BoxGeometry(5.6,.12,11),new THREE.MeshStandardMaterial({map:stoneTexture(),color:x%16?0x676e77:0x7a828c,roughness:.88}));slab.position.set(x,.08,0);slab.receiveShadow=true;scene.add(slab)}
 for(let i=0;i<42;i++){let side=i%2?1:-1,z=side*(11+Math.random()*18),x=-58+Math.random()*116;makeTree(x,z,rand(.7,1.45))}for(let i=0;i<24;i++)makeBush(-58+Math.random()*116,(i%2?1:-1)*rand(9,25),rand(.7,1.4));for(let i=0;i<20;i++)makeRock(-58+Math.random()*116,(i%2?1:-1)*rand(10,27),rand(.65,1.45));for(let i=0;i<18;i++)makeCrystal(-58+Math.random()*116,(i%2?1:-1)*rand(10,25),i%2?0x46cfff:0xff5577);makeRiver();}
function makeGroundTexture(){let c=document.createElement('canvas');c.width=c.height=512;let x=c.getContext('2d');let g=x.createLinearGradient(0,0,512,512);g.addColorStop(0,'#1f4a2a');g.addColorStop(.5,'#1a4123');g.addColorStop(1,'#1d4627');x.fillStyle=g;x.fillRect(0,0,512,512);for(let i=0;i<260;i++){x.fillStyle=`rgba(${10+Math.random()*25|0},${50+Math.random()*45|0},${20+Math.random()*20|0},${.08+Math.random()*.12})`;x.beginPath();x.ellipse(Math.random()*512,Math.random()*512,rand(14,60),rand(8,30),Math.random()*3.14,0,6.3);x.fill()}for(let i=0;i<9000;i++){let l=Math.random();x.fillStyle=l>.6?'#2f6a3a':l>.25?'#24502c':'#12301a';x.globalAlpha=.5;x.fillRect(Math.random()*512,Math.random()*512,1,rand(2,5));x.globalAlpha=1}for(let i=0;i<900;i++){x.fillStyle=Math.random()>.5?'#dce8b8':'#8fd08a';x.globalAlpha=.12;x.fillRect(Math.random()*512,Math.random()*512,1,2);x.globalAlpha=1}return c}
let waterTex=null,_stoneTex=null,_glowTex=null;
function stoneTexture(){if(_stoneTex)return _stoneTex;let c=document.createElement('canvas');c.width=c.height=256;let x=c.getContext('2d');x.fillStyle='#565c63';x.fillRect(0,0,256,256);for(let ty=0;ty<4;ty++)for(let tx=0;tx<5;tx++){let off=(ty%2)*32,px=tx*64-off,py=ty*64,sh=rand(-10,10);x.fillStyle=`rgb(${96+sh|0},${102+sh|0},${110+sh|0})`;x.fillRect(px+2,py+2,60,60);x.fillStyle='rgba(255,255,255,.08)';x.fillRect(px+2,py+2,60,3);x.fillStyle='rgba(0,0,0,.25)';x.fillRect(px+2,py+59,60,3)}for(let i=0;i<2600;i++){x.fillStyle=Math.random()>.5?'rgba(255,255,255,.04)':'rgba(0,0,0,.06)';x.fillRect(Math.random()*256,Math.random()*256,2,2)}_stoneTex=new THREE.CanvasTexture(c);_stoneTex.wrapS=_stoneTex.wrapT=THREE.RepeatWrapping;return _stoneTex}
function glowSprite(color,s){if(!_glowTex){let c=document.createElement('canvas');c.width=c.height=128;let x=c.getContext('2d'),g=x.createRadialGradient(64,64,4,64,64,62);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.35,'rgba(255,255,255,.45)');g.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=g;x.fillRect(0,0,128,128);_glowTex=new THREE.CanvasTexture(c)}let sp=new THREE.Sprite(new THREE.SpriteMaterial({map:_glowTex,color,transparent:true,opacity:.85,blending:THREE.AdditiveBlending,depthWrite:false}));sp.scale.setScalar(s);return sp}
function makeTree(x,z,s){let g=new THREE.Group(),tr=new THREE.Mesh(new THREE.CylinderGeometry(.25,.4,2.5,7),new THREE.MeshStandardMaterial({color:0x463222})),top=new THREE.Mesh(new THREE.ConeGeometry(1.4,3.4,8),new THREE.MeshStandardMaterial({color:0x173b2a,roughness:1}));tr.position.y=1.25;top.position.y=3.4;g.add(tr,top);g.position.set(x,0,z);g.scale.setScalar(s);scene.add(g)}
function makeBush(x,z,s){let g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:0x1e6a3d,roughness:1});for(let i=0;i<7;i++){let b=new THREE.Mesh(new THREE.ConeGeometry(.42,.95,6),mat);b.position.set(rand(-.7,.7),.45,rand(-.55,.55));b.rotation.z=rand(-.35,.35);g.add(b)}g.position.set(x,0,z);g.scale.setScalar(s);scene.add(g)}
function makeRock(x,z,s){let m=new THREE.Mesh(new THREE.DodecahedronGeometry(1,0),new THREE.MeshStandardMaterial({color:0x566267,roughness:.92}));m.position.set(x,.65*s,z);m.scale.set(s*1.25,s*.7,s);m.rotation.set(rand(-.2,.2),rand(0,6.2),rand(-.15,.15));m.castShadow=m.receiveShadow=true;scene.add(m)}
function makeCrystal(x,z,c){let m=new THREE.Mesh(new THREE.OctahedronGeometry(.45,0),new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:1.4,roughness:.25}));m.position.set(x,.55,z);scene.add(m)}
function makeRiver(){let c=document.createElement('canvas');c.width=128;c.height=512;let x=c.getContext('2d'),g=x.createLinearGradient(0,0,128,0);g.addColorStop(0,'#135266');g.addColorStop(.5,'#1d7b90');g.addColorStop(1,'#135266');x.fillStyle=g;x.fillRect(0,0,128,512);for(let i=0;i<130;i++){x.strokeStyle=`rgba(${150+Math.random()*105|0},${220+Math.random()*35|0},255,${.05+Math.random()*.12})`;x.lineWidth=rand(.6,2.2);let sx=Math.random()*128,sy=Math.random()*512;x.beginPath();x.moveTo(sx,sy);x.quadraticCurveTo(sx+rand(-14,14),sy+rand(18,50),sx+rand(-8,8),sy+rand(60,110));x.stroke()}waterTex=new THREE.CanvasTexture(c);waterTex.wrapS=waterTex.wrapT=THREE.RepeatWrapping;waterTex.repeat.set(1,3);let bank=new THREE.Mesh(new THREE.PlaneGeometry(8.8,66),new THREE.MeshStandardMaterial({color:0x122e38,roughness:1}));bank.rotation.x=-Math.PI/2;bank.position.y=.02;bank.receiveShadow=true;scene.add(bank);let r=new THREE.Mesh(new THREE.PlaneGeometry(7,66),new THREE.MeshStandardMaterial({map:waterTex,transparent:true,opacity:.82,roughness:.15,metalness:.3,emissive:0x0d3d4d,emissiveIntensity:.5}));r.rotation.x=-Math.PI/2;r.position.y=.035;scene.add(r)}

function spawnHero(id,team,pos,player=false){let root=new THREE.Group(),model=cloneSkinnedModel(templates[id]);model.scale.setScalar(3.15);model.position.y=.03;root.add(model);root.position.copy(pos);scene.add(root);tintTeam(model,team);addHeroGear(root,id,team,player);let mixer=new THREE.AnimationMixer(model),clips={};for(const a of animations[id])clips[a.name]=mixer.clipAction(a);clips.idle?.play();mixers.push(mixer);let h={kind:'hero',id,def:defs[id],team,root,model,mixer,clips,anim:'idle',pos:root.position,spawn:pos.clone(),player,hp:defs[id].hp,maxHp:defs[id].hp,mana:100,atk:defs[id].atk,range:defs[id].range,speed:defs[id].speed,dead:false,respawn:0,cd:[0,0,0,0],shield:0,buff:0,invis:0,kills:0,deaths:0,level:1,xp:0,gold:400,goldT:0,armor:0,lifesteal:0,cdr:0,items:[],lastDir:new THREE.Vector3(team? -1:1,0,0)};makeBar(h);game.heroes.push(h);if(player)game.player=h;return h}
function tintTeam(model,team){model.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.emissive=new THREE.Color(team?0x210008:0x001728);o.material.emissiveIntensity=.35}})}
function addHeroGear(root,id,team,player=false){const mat=new THREE.MeshStandardMaterial({color:defs[id].color,metalness:.55,roughness:.35,emissive:defs[id].color,emissiveIntensity:.22});let weapon;if(id===0){weapon=new THREE.Mesh(new THREE.CylinderGeometry(.07,.09,2.4,8),mat);weapon.rotation.z=.25;weapon.position.set(.86,1.18,.18);let orb=new THREE.Mesh(new THREE.IcosahedronGeometry(.26),mat);orb.position.y=1.25;weapon.add(orb);let halo=new THREE.Mesh(new THREE.TorusGeometry(.42,.055,8,24),mat);halo.rotation.x=Math.PI/2;halo.position.set(0,2.18,0);root.add(halo)}else if(id===1){weapon=new THREE.Mesh(new THREE.BoxGeometry(1.05,1.35,.2),mat);weapon.position.set(.95,1,.18);for(const s of[-1,1]){let pad=new THREE.Mesh(new THREE.DodecahedronGeometry(.28),mat);pad.position.set(s*.72,1.48,0);root.add(pad)}}else if(id===2){weapon=new THREE.Group();for(const s of[-1,1]){let b=new THREE.Mesh(new THREE.BoxGeometry(.12,1.45,.12),mat);b.position.set(s*.72,1.05,.25);b.rotation.z=s*.42;weapon.add(b)}}else if(id===3){weapon=new THREE.Mesh(new THREE.TorusGeometry(.74,.075,7,22,Math.PI*1.48),mat);weapon.rotation.y=Math.PI/2;weapon.position.set(.88,1.18,.18);let quiver=new THREE.Mesh(new THREE.CylinderGeometry(.16,.2,1.15,8),mat);quiver.rotation.z=.24;quiver.position.set(-.6,1.22,-.28);root.add(quiver)}else if(id===4){weapon=new THREE.Mesh(new THREE.CylinderGeometry(.22,.29,.62,8),mat);weapon.position.set(.78,1.25,.35);let glow=new THREE.PointLight(defs[id].color,1.8,5);weapon.add(glow);let crown=new THREE.Mesh(new THREE.ConeGeometry(.36,.45,6),mat);crown.position.set(0,2.12,0);root.add(crown)}else{weapon=new THREE.Group();for(const s of[-1,1]){let f=new THREE.Mesh(new THREE.IcosahedronGeometry(.3),mat);f.position.set(s*.72,1.05,.4);weapon.add(f)}}root.add(weapon);let ring=new THREE.Mesh(new THREE.TorusGeometry(player?1.15:.92,player?.065:.045,8,36),new THREE.MeshBasicMaterial({color:player?0xffe46a:(team?0xff4265:0x3fcfff)}));ring.rotation.x=Math.PI/2;ring.position.y=.05;root.add(ring)}
function makeBar(e){let c=document.createElement('canvas');c.width=192;c.height=48;let tex=new THREE.CanvasTexture(c),spr=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,depthTest:false}));spr.scale.set(e.kind==='hero'?3.25:2.15,e.kind==='hero'?.82:.54,1);spr.position.y=e.kind==='hero'?3.15:1.35;e.root.add(spr);e.bar={c,ctx:c.getContext('2d'),tex,spr};updateBar(e)}
function updateBar(e){if(!e.bar)return;let x=e.bar.ctx;x.clearRect(0,0,192,48);if(e.kind==='hero'){x.font='bold 15px sans-serif';x.textAlign='center';x.fillStyle='#fff';x.shadowColor='#000';x.shadowBlur=4;x.fillText(`Lv.${e.level||1}  ${e.def?.name||''}`,96,15);x.shadowBlur=0}x.fillStyle='#160711';x.fillRect(10,22,172,14);x.fillStyle=e.team?'#ff5473':'#46d2ff';x.fillRect(10,22,172*clamp(e.hp/e.maxHp,0,1),14);x.strokeStyle='#fff9';x.lineWidth=2;x.strokeRect(10,22,172,14);e.bar.tex.needsUpdate=true}

function spawnStructures(){for(const team of[0,1]){let sx=team?55:-55,tx=team?35:-35;game.structures.push(makeStructure(team,'core',sx,0),makeStructure(team,'tower',tx,0))}}
function makeStructure(team,kind,x,z){let root=new THREE.Group(),c=team?0xff365e:0x31caff,dark=team?0x3a1220:0x0e2c3e,st=stoneTexture();
 if(kind==='tower'){let t1=new THREE.Mesh(new THREE.CylinderGeometry(2.3,2.9,.8,10),new THREE.MeshStandardMaterial({map:st,color:0xa8afb8,roughness:.85}));t1.position.y=.4;let t2=new THREE.Mesh(new THREE.CylinderGeometry(1.35,1.75,3.4,10),new THREE.MeshStandardMaterial({map:st,color:0x99a1ab,roughness:.85}));t2.position.y=2.4;let band=new THREE.Mesh(new THREE.TorusGeometry(1.6,.14,8,20),new THREE.MeshStandardMaterial({color:dark,metalness:.6,roughness:.4}));band.rotation.x=Math.PI/2;band.position.y=1.15;let top=new THREE.Mesh(new THREE.CylinderGeometry(1.9,1.5,.55,10),new THREE.MeshStandardMaterial({map:st,color:0xb2bac4,roughness:.8}));top.position.y=4.35;[t1,t2,band,top].forEach(m=>{m.castShadow=true;m.receiveShadow=true;root.add(m)});for(let i=0;i<8;i++){let cr=new THREE.Mesh(new THREE.BoxGeometry(.42,.5,.42),new THREE.MeshStandardMaterial({map:st,color:0xa5adb7}));cr.position.set(Math.cos(i/8*6.283)*1.62,4.85,Math.sin(i/8*6.283)*1.62);cr.castShadow=true;root.add(cr)}let gem=new THREE.Mesh(new THREE.OctahedronGeometry(.62),new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:2.2}));gem.position.y=5.65;root.add(gem);root.userData.gem=gem;let gl=glowSprite(c,3.2);gl.position.y=5.65;root.add(gl)}
 else{let plinth=new THREE.Mesh(new THREE.CylinderGeometry(3.4,4,.9,12),new THREE.MeshStandardMaterial({map:st,color:0xa8afb8,roughness:.85}));plinth.position.y=.45;plinth.castShadow=true;plinth.receiveShadow=true;root.add(plinth);for(let i=0;i<5;i++){let p=new THREE.Mesh(new THREE.CylinderGeometry(.28,.36,3.1,8),new THREE.MeshStandardMaterial({map:st,color:0x99a1ab}));p.position.set(Math.cos(i/5*6.283)*2.6,2.4,Math.sin(i/5*6.283)*2.6);p.castShadow=true;root.add(p)}let ringT=new THREE.Mesh(new THREE.TorusGeometry(2.6,.2,8,26),new THREE.MeshStandardMaterial({map:st,color:0xb2bac4}));ringT.rotation.x=Math.PI/2;ringT.position.y=4;ringT.castShadow=true;root.add(ringT);let gem=new THREE.Mesh(new THREE.IcosahedronGeometry(1.35,1),new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:1.9,transparent:true,opacity:.94}));gem.position.y=2.7;root.add(gem);root.userData.gem=gem;let gl=glowSprite(c,5.5);gl.position.y=2.7;root.add(gl)}
 root.position.set(x,0,z);scene.add(root);let e={kind,team,root,pos:root.position,hp:kind==='core'?3000:1650,maxHp:kind==='core'?3000:1650,range:kind==='core'?11:10,atk:kind==='core'?115:90,cd:0,dead:false};makeBar(e);e.bar.spr.position.y=kind==='core'?5.2:6.7;return e}
function spawnWave(){for(const team of[0,1])for(let i=0;i<4;i++)spawnMinion(team,i)}
function spawnMinion(team,i){let root=new THREE.Group(),gear=new THREE.Group(),tc=team?0xa32642:0x18799f,ac=team?0xff6a80:0x5bdcff,ranged=i===3;
 let body=new THREE.Mesh(new THREE.CapsuleGeometry(.3,.5,3,8),new THREE.MeshStandardMaterial({color:tc,roughness:.65,metalness:.15}));body.position.y=.72;body.castShadow=true;
 let head=new THREE.Mesh(new THREE.SphereGeometry(.26,10,8),new THREE.MeshStandardMaterial({color:0xf0d5b5,roughness:.8}));head.position.y=1.38;head.castShadow=true;
 let helm=new THREE.Mesh(new THREE.SphereGeometry(.29,10,8,0,6.283,0,1.5),new THREE.MeshStandardMaterial({color:ac,metalness:.6,roughness:.35}));helm.position.y=1.42;
 let belt=new THREE.Mesh(new THREE.TorusGeometry(.31,.05,6,12),new THREE.MeshStandardMaterial({color:0x332b22,roughness:.8}));belt.rotation.x=Math.PI/2;belt.position.y=.62;
 let sl=new THREE.Mesh(new THREE.SphereGeometry(.14,8,6),new THREE.MeshStandardMaterial({color:ac,metalness:.5}));sl.position.set(.34,1.1,0);let sr=sl.clone();sr.position.x=-.34;
 gear.add(body,head,helm,belt,sl,sr);
 if(ranged){let staff=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,1.5,6),new THREE.MeshStandardMaterial({color:0x6b4b2c,roughness:.8}));staff.position.set(.4,1,.12);staff.rotation.z=.28;let orb=new THREE.Mesh(new THREE.SphereGeometry(.12,8,6),new THREE.MeshStandardMaterial({color:ac,emissive:ac,emissiveIntensity:2}));orb.position.set(.6,1.72,.12);gear.add(staff,orb)}
 else{let bl=new THREE.Mesh(new THREE.BoxGeometry(.09,.85,.2),new THREE.MeshStandardMaterial({color:0xcfd6de,metalness:.85,roughness:.25}));bl.position.set(.44,1.05,.14);bl.rotation.z=.32;let hilt=new THREE.Mesh(new THREE.BoxGeometry(.26,.07,.07),new THREE.MeshStandardMaterial({color:0x8a6a30,metalness:.7}));hilt.position.set(.31,.72,.14);hilt.rotation.z=.32;let sh=new THREE.Mesh(new THREE.CylinderGeometry(.3,.3,.07,10),new THREE.MeshStandardMaterial({color:tc,metalness:.4,roughness:.5}));sh.rotation.z=Math.PI/2;sh.position.set(-.4,.95,.1);gear.add(bl,hilt,sh)}
 root.add(gear);root.position.set(team?51:-51,0,(i-1.5)*.8);scene.add(root);let e={kind:'minion',team,root,gear,walk:Math.random()*6,pos:root.position,hp:250,maxHp:250,atk:i===3?30:24,range:i===3?5.2:1.25,speed:3.2,cd:0,dead:false,lastDir:new THREE.Vector3(team?-1:1,0,0)};makeBar(e);game.minions.push(e)}

const all=()=>[...game.heroes,...game.minions,...game.structures], enemies=o=>all().filter(e=>e.team!==o.team&&!e.dead&&e.hp>0&&!(e.kind==='core'&&game.structures.some(s=>s.team===e.team&&s.kind==='tower'&&!s.dead))), friends=o=>game.heroes.filter(e=>e.team===o.team&&!e.dead);
function nearest(o,list=enemies(o)){let t=null,d=1e9;for(const e of list){let q=o.pos.distanceTo(e.pos);if(q<d){d=q;t=e}}return[t,d]}
function face(o,t){if(!t)return;let dx=t.pos.x-o.pos.x,dz=t.pos.z-o.pos.z;o.root.rotation.y=Math.atan2(dx,dz);o.lastDir.set(dx,0,dz).normalize()}
function setAnim(h,n,once=false){if(h.anim===n)return;let next=h.clips[n]||h.clips.idle;if(!next)return;let cur=h.clips[h.anim];cur?.fadeOut(.12);next.reset().fadeIn(.12);next.setLoop(once?THREE.LoopOnce:THREE.LoopRepeat,once?1:Infinity);next.clampWhenFinished=once;next.play();h.anim=n;if(once)setTimeout(()=>{if(!h.dead)setAnim(h,'idle')},480)}
function hurt(src,t,n){if(!t||t.dead)return;n*=t.shield>0?.58:1;if(t.armor)n*=(1-Math.min(.5,t.armor));t.hp-=n;updateBar(t);floatText(t.pos,'-'+Math.round(n),0xff6680);pulse(t.pos,src?.team?0xff405f:0x3fd8ff,.8);if(t.kind==='hero')flashModel(t);if(src?.kind==='hero'&&src.lifesteal)heal(src,n*src.lifesteal);if(t.hp<=0)kill(src,t)}
function heal(t,n){t.hp=Math.min(t.maxHp,t.hp+n);updateBar(t);floatText(t.pos,'+'+Math.round(n),0x65ff96);pulse(t.pos,0x59ff91,.65)}
function kill(src,t){t.hp=0;t.dead=true;updateBar(t);
 if(t.kind==='hero'){burst(t.pos,t.team?0xff5473:0x46d2ff);shake(.45);hitstop(.09);t.deaths++;t.respawn=Math.min(42,8+(t.level||1)*2.2+game.time/60*1.6);t.root.visible=false;setAnim(t,'die',true);if(src?.kind==='hero'){src.kills++;src.xp+=100;gold(src,300);src.team?game.redKills++:game.blueKills++;feed(`${src.def.name} 击败 ${t.def.name}`,src.team?0xff6883:0x64ddff);levelCheck(src)}}
 else{t.root.visible=false;
  if(t.kind==='minion'){pulse(t.pos,t.team?0xff5874:0x50d6ff,1.1);if(src?.kind==='hero'){gold(src,38);src.xp+=25;levelCheck(src);if(src.player)floatText(t.pos,'+38',0xffd45c)}}
  if(t.kind==='tower'){burst(t.pos,0xffd36b);ring(t.pos,0xffd36b,5.5);scorch(t.pos,3.2);shake(.9);hitstop(.12);if(src?.kind==='hero')gold(src,150);feed(`${t.team?'赤渊':'苍穹'}防御塔已经倒塌！`,0xffd36b)}
  if(t.kind==='core'){burst(t.pos,t.team?0xff5473:0x46d2ff);shake(1.2);finish(src?.team===0)}}}
function levelCheck(h){let need=h.level*120;if(h.xp>=need&&h.level<12){h.xp-=need;h.level++;h.maxHp+=70;h.hp+=70;h.atk+=8;updateBar(h);floatText(h.pos,'升级！',0xffdb65)}}
function pickTarget(h,mode){
 if(!mode)return nearest(h)[0];
 const inRange=enemies(h).filter(e=>!e.dead&&h.pos.distanceTo(e.pos)<=h.range+1);
 if(mode==='tower'){return inRange.filter(e=>e.kind==='tower'||e.kind==='core').sort((a,b)=>h.pos.distanceTo(a.pos)-h.pos.distanceTo(b.pos))[0]||null}
 const ms=inRange.filter(e=>e.kind==='minion');if(!ms.length)return null;
 const killable=ms.filter(e=>e.hp<=h.atk);return (killable.length?killable:ms).sort((a,b)=>a.hp-b.hp)[0]}
function basic(h,mode,forced){if(!h||h.dead||h.cd[3]>0)return;let t=forced||pickTarget(h,mode);
 if(!t){if(h.player&&mode)feed(mode==='tower'?'射程内没有防御塔':'射程内没有小兵',0xffab6a);return}
 let d=h.pos.distanceTo(t.pos);if(d>h.range+1)return;h.cd[3]=.72;face(h,t);setAnim(h,h.range>3?'holding-right-shoot':'attack-melee-right',true);if(h.range>3)projectile(h,t,h.atk,h.def.color,18);else setTimeout(()=>{if(!t.dead&&h.pos.distanceTo(t.pos)<h.range+1.4)hurt(h,t,h.atk)},220)}
function projectile(src,t,dmg,color,speed=20){let m=new THREE.Mesh(new THREE.SphereGeometry(.12,8,6),new THREE.MeshBasicMaterial({color:0xffffff}));m.add(glowSprite(color,1.15));m.position.copy(src.pos).add(new THREE.Vector3(0,1.2,0));scene.add(m);game.shots.push({mesh:m,pos:m.position,target:t,src,dmg,speed,color})}
function cast(h,s){if(!h||h.dead||h.cd[s]>0||h.mana<(s===2?40:22))return;let[t,d]=nearest(h);h.mana-=s===2?40:22;h.cd[s]=[5,9,20][s]*(1-(h.cdr||0));let id=h.id;setAnim(h,id===3?'holding-both-shoot':'attack-melee-left',true);
 if(id===0){if(s===0&&t)enemies(h).sort((a,b)=>a.pos.distanceTo(t.pos)-b.pos.distanceTo(t.pos)).slice(0,3).forEach((e,i)=>{lightning(h.pos,e.pos,0x6fcfff);hurt(h,e,130-i*25)});if(s===1&&t)zone(t.pos,3.8,3,h.team,38,0x4abfff);if(s===2)enemies(h).filter(e=>e.kind==='hero').forEach(e=>{lightning(new THREE.Vector3(e.pos.x,12,e.pos.z),e.pos,0xb6e7ff);hurt(h,e,220)})}
 if(id===1){if(s===0&&t&&d<4){hurt(h,t,170);ring(t.pos,0xe6c078,2.4)}if(s===1)friends(h).forEach(a=>{if(a.pos.distanceTo(h.pos)<8)a.shield=5});if(s===2){ring(h.pos,0xffd37a,7);enemies(h).filter(e=>e.pos.distanceTo(h.pos)<7).forEach(e=>hurt(h,e,210))}}
 if(id===2){if(s===0&&t){let v=t.pos.clone().sub(h.pos).setY(0),l=Math.min(6,Math.max(0,v.length()-1));v.normalize();h.pos.addScaledVector(v,l);face(h,t);hurt(h,t,155);trail(h.pos,0xca75ff)}if(s===1){h.invis=3.5;h.buff=3.5;h._opaque=false;h.root.traverse(o=>{if(o.material){o.material.transparent=true;o.material.opacity=.28}})}if(s===2&&t){trail(t.pos,0xe8b2ff);hurt(h,t,t.hp/t.maxHp<.4?430:240)}}
 if(id===3){if(s===0&&t)projectile(h,t,190,0x83ffce,28);if(s===1){h.buff=5;trail(h.pos,0x70ffd0)}if(s===2&&t)zone(t.pos,4.7,4.2,h.team,48,0x72efc2)}
 if(id===4){if(s===0&&t){projectile(h,t,105,0xa6ff8d,20);let q=nearest(t,enemies(h).filter(e=>e!==t))[0];if(q)projectile(h,q,75,0x7cffb2,20)}if(s===1)friends(h).filter(a=>a.pos.distanceTo(h.pos)<10).forEach(a=>heal(a,190));if(s===2){friends(h).forEach(a=>{a.shield=7;heal(a,100)});ring(h.pos,0xaaff9a,9)}}
 if(id===5){if(s===0&&t&&d<4){hurt(h,t,180);heal(h,65);burst(t.pos,0xff6b40)}if(s===1){h.buff=7;h.shield=3;trail(h.pos,0xff7c48)}if(s===2){h.buff=10;h.atk+=32;setTimeout(()=>h.atk-=32,10000);ring(h.pos,0xff492f,6)}}
}
function zone(pos,r,life,team,dmg,color){
 let warn=new THREE.Mesh(new THREE.RingGeometry(r*.93,r,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.85,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false}));warn.rotation.x=-Math.PI/2;warn.position.copy(pos);warn.position.y=.1;scene.add(warn);
 let mesh=new THREE.Mesh(new THREE.CircleGeometry(.1,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.25,side:THREE.DoubleSide,depthWrite:false}));mesh.rotation.x=-Math.PI/2;mesh.position.copy(pos);mesh.position.y=.08;scene.add(mesh);
 game.zones.push({mesh,warn,color,pos:mesh.position,r,life:life+.5,windup:.5,team,dmg,tick:.5})}
/* ===== FX 特效系统:加法混合发光粒子 ===== */
function fxSprite(pos,color,size,life,vel,opts={}){let sp=glowSprite(color,size);sp.position.copy(pos);scene.add(sp);game.effects.push({mesh:sp,life,maxLife:life,vel,grav:opts.grav||0,shrink:opts.shrink||0,fadeFrom:opts.fadeFrom});return sp}
function ring(pos,color,r){let mk=(rr,op,grow)=>{let m=new THREE.Mesh(new THREE.RingGeometry(rr*.86,rr,56),new THREE.MeshBasicMaterial({color,transparent:true,opacity:op,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.copy(pos);m.position.y=.12;scene.add(m);game.effects.push({mesh:m,life:.5,grow})};mk(r,1,2.2);mk(r*.6,.5,3.4);fxSprite(pos.clone().add(new THREE.Vector3(0,.5,0)),color,r*1.5,.26,null,{shrink:-1.6})}
function pulse(pos,color,r){fxSprite(pos.clone().add(new THREE.Vector3(0,1.1,0)),0xffffff,r*1.4,.11,null,{shrink:-2});for(let i=0;i<5;i++){let a=Math.random()*6.283,sp=rand(3,7);fxSprite(pos.clone().add(new THREE.Vector3(0,1.1,0)),color,rand(.25,.5),rand(.18,.32),new THREE.Vector3(Math.cos(a)*sp,rand(1,4),Math.sin(a)*sp),{grav:-14,shrink:2})}}
function trail(pos,color){for(let i=0;i<10;i++){let a=Math.random()*6.283,sp=rand(1.5,4.5);fxSprite(pos.clone().add(new THREE.Vector3(rand(-.4,.4),rand(.2,1.6),rand(-.4,.4))),color,rand(.5,1.1),rand(.4,.7),new THREE.Vector3(Math.cos(a)*sp,rand(1.5,3.5),Math.sin(a)*sp),{grav:-6,shrink:1.6})}}
function burst(pos,color){fxSprite(pos.clone().add(new THREE.Vector3(0,1,0)),0xffffff,3.4,.14,null,{shrink:-3});fxSprite(pos.clone().add(new THREE.Vector3(0,1,0)),color,2.6,.3,null,{shrink:-1});for(let i=0;i<20;i++){let a=Math.random()*6.283,sp=rand(5,12);fxSprite(pos.clone().add(new THREE.Vector3(0,1,0)),Math.random()<.3?0xffffff:color,rand(.3,.7),rand(.3,.55),new THREE.Vector3(Math.cos(a)*sp,rand(2,8),Math.sin(a)*sp),{grav:-22,shrink:1.8})}ring(pos,color,1.6);scorch(pos,1.4)}
function scorch(pos,r){let m=new THREE.Mesh(new THREE.CircleGeometry(r,26),new THREE.MeshBasicMaterial({color:0x000000,transparent:true,opacity:.4,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.copy(pos);m.position.y=.055;scene.add(m);game.effects.push({mesh:m,life:5,fadeFrom:.4})}
function lightning(a,b,color){for(const co of [[0xffffff,1],[color,.8]]){let pts=[a.clone().add(new THREE.Vector3(0,1.1,0))];for(let i=1;i<6;i++)pts.push(a.clone().lerp(b,i/6).add(new THREE.Vector3(rand(-.5,.5),rand(.4,1.9),rand(-.5,.5))));pts.push(b.clone().add(new THREE.Vector3(0,1,0)));let line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:co[0],transparent:true,opacity:co[1],blending:THREE.AdditiveBlending}));scene.add(line);game.effects.push({mesh:line,life:.22})}fxSprite(b.clone().add(new THREE.Vector3(0,1,0)),color,1.8,.18,null,{shrink:-2})}
function shake(amt){if(game)game.shake=Math.max(game.shake||0,amt)}
function hitstop(t){if(game)game.slow=Math.max(game.slow||0,t)}
function flashModel(h){if(!h.model)return;h.model.traverse(o=>{if(o.material&&o.material.emissive){if(o.userData._em===undefined)o.userData._em=o.material.emissiveIntensity;o.material.emissiveIntensity=2.4}});setTimeout(()=>{if(h.model)h.model.traverse(o=>{if(o.material&&o.material.emissive)o.material.emissiveIntensity=o.userData._em!==undefined?o.userData._em:.35})},70)}

function movePlayer(h,dt){let x=(keys.d?1:0)-(keys.a?1:0)+joy.x,z=(keys.s?1:0)-(keys.w?1:0)+joy.y,l=Math.hypot(x,z);if(l>.12){x/=l;z/=l;let sp=h.speed*(h.buff>0?1.3:1);h.pos.x=clamp(h.pos.x+x*sp*dt,-60,60);h.pos.z=clamp(h.pos.z+z*sp*dt,-29,29);h.root.rotation.y=Math.atan2(x,z);h.lastDir.set(x,0,z);setAnim(h,'sprint')}else setAnim(h,'idle')}
function useUtility(type){if(!game||game.over||!game.player||game.player.dead||game.utility[type]>0)return;let p=game.player;if(type==='recall'){game.utility.recall=18;ring(p.pos,0x55cfff,3.3);trail(p.pos,0x7de6ff);p.pos.copy(p.spawn);p.hp=p.maxHp;p.mana=100;updateBar(p);feed(`${p.def.name} 已返回泉水`,0x7fe6ff)}else if(type==='heal'){game.utility.heal=14;heal(p,p.maxHp*.3);friends(p).filter(a=>a!==p&&a.pos.distanceTo(p.pos)<7).forEach(a=>heal(a,a.maxHp*.14));ring(p.pos,0x72ff91,4)}else if(type==='flash'){game.utility.flash=12;let from=p.pos.clone(),dir=p.lastDir.clone();if(dir.lengthSq()<.01)dir.set(1,0,0);p.pos.x=clamp(p.pos.x+dir.x*6.5,-60,60);p.pos.z=clamp(p.pos.z+dir.z*6.5,-29,29);trail(from,0xffd55c);trail(p.pos,0xffe58a)}}
function step(h,dir,dt,rate=1){let v=dir.clone().setY(0);if(v.lengthSq()<1e-4){setAnim(h,'idle');return}v.normalize();let sp=h.speed*(h.buff>0?1.25:1)*rate;h.pos.x=clamp(h.pos.x+v.x*sp*dt,-60,60);h.pos.z=clamp(h.pos.z+v.z*sp*dt,-29,29);h.root.rotation.y=Math.atan2(v.x,v.z);h.lastDir.copy(v);setAnim(h,rate>.85?'sprint':'walk')}
function towerThreat(h,pos){return game.structures.find(s=>!s.dead&&s.team!==h.team&&s.pos.distanceTo(pos)<s.range+1.5)}
function aiHero(h,dt){
 const es=enemies(h).filter(e=>!e.dead),hpr=h.hp/h.maxHp;
 /* 看门狗:连续4秒几乎没有位移则强制推进,防止任何分支把AI卡住 */
 if(!h._lastPos)h._lastPos=h.pos.clone();
 if(h.pos.distanceTo(h._lastPos)<.35){h._stillT=(h._stillT||0)+dt}else{h._stillT=0;h._lastPos.copy(h.pos)}
 if(h._stillT>4){h.retreat=false;const core=game.structures.find(c=>c.kind==='core'&&c.team!==h.team);if(core){step(h,core.pos.clone().sub(h.pos),dt,1);if(h.pos.distanceTo(h._lastPos)>.35){h._stillT=0;h._lastPos.copy(h.pos)}return}}
 const eh=es.filter(e=>e.kind==='hero'&&e.invis<=0),em=es.filter(e=>e.kind==='minion'),et=es.filter(e=>e.kind==='tower'||e.kind==='core');
 const mates=friends(h).filter(a=>a!==h),myMinions=game.minions.filter(m=>!m.dead&&m.team===h.team);

 /* —— 撤退与回泉:低血回家,补满再战 —— */
 if(hpr<.32)h.retreat=true;
 if(h.retreat){
  if(hpr>.86){h.retreat=false}
  else{
   const near=eh.filter(e=>e.pos.distanceTo(h.pos)<h.range+4);
   if(near.length&&h.cd[1]<=0&&h.mana>=22)cast(h,1);               // 追杀时交保命/位移技能
   if(near.length&&h.cd[3]<=0&&near[0].pos.distanceTo(h.pos)<=h.range+1)basic(h,null,near[0]);
   if(h.pos.distanceTo(h.spawn)>2.5){step(h,h.spawn.clone().sub(h.pos),dt,1);return}
   setAnim(h,'idle');return}}

 /* —— 目标优先级:可击杀英雄 > 附近英雄 > 小兵(补刀推线) > 防御塔 —— */
 let t=null,intent='';
 const reach=h.range+5.5;
 const hurtHeroes=eh.filter(e=>e.pos.distanceTo(h.pos)<reach+3).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp);
 const finisher=hurtHeroes.find(e=>e.hp<=h.atk*2.4);
 if(finisher){t=finisher;intent='chase'}
 else if(hurtHeroes.length&&hurtHeroes[0].pos.distanceTo(h.pos)<reach){t=hurtHeroes[0];intent='fight'}
 else{
  const lastHit=em.filter(e=>e.pos.distanceTo(h.pos)<h.range+3&&e.hp<=h.atk).sort((a,b)=>a.hp-b.hp)[0];
  if(lastHit){t=lastHit;intent='farm'}
  else if(em.length){t=em.sort((a,b)=>h.pos.distanceTo(a.pos)-h.pos.distanceTo(b.pos))[0];intent='farm'}
  else if(et.length){t=et.sort((a,b)=>h.pos.distanceTo(a.pos)-h.pos.distanceTo(b.pos))[0];intent='push'}}
 if(!t){step(h,new THREE.Vector3(h.team?-1:1,0,-h.pos.z*.05),dt,.7);return}

 const d=h.pos.distanceTo(t.pos),melee=h.range<3.2;

 /* —— 塔下不送:没有己方小兵顶塔时,不进入敌方塔范围 —— */
 const threat=towerThreat(h,t.pos);
 if(threat&&intent!=='push'&&!myMinions.some(m=>m.pos.distanceTo(threat.pos)<threat.range)){
  if(h.pos.distanceTo(threat.pos)<threat.range+2){step(h,h.pos.clone().sub(threat.pos),dt,1);return}}
 if(intent==='push'&&myMinions.filter(m=>m.pos.distanceTo(t.pos)<12).length===0&&hpr<.9&&h.pos.distanceTo(h.spawn)>9){
  step(h,h.spawn.clone().sub(h.pos),dt,.8);return}                  // 无兵线不强推,但已在泉水则不再后退

 /* —— 走位:远程放风筝,近战贴脸 —— */
 const ideal=melee?1.8:h.range*.82;
 if(d>ideal+.6)step(h,t.pos.clone().sub(h.pos),dt,intent==='chase'?1:.85);
 else if(!melee&&d<h.range*.45&&t.kind==='hero'){step(h,h.pos.clone().sub(t.pos),dt,.9);face(h,t)}
 else{setAnim(h,'idle');face(h,t)}

 /* —— 出手:普攻优先补刀,技能按价值释放 —— */
 if(d<=h.range+1)basic(h,null,t);
 if(t.kind!=='hero')return;
 const cluster=eh.filter(e=>e.pos.distanceTo(t.pos)<6).length;
 if(d<h.range+3){
  if(h.cd[2]<=0&&h.mana>=40&&(cluster>=2||t.hp/t.maxHp<.5))cast(h,2);      // 大招:多人或残血
  else if(h.cd[0]<=0&&h.mana>=22)cast(h,0);                                // 一技能:主力输出
  else if(h.cd[1]<=0&&h.mana>=22&&(h.id===1||h.id===4||hpr<.6||cluster>=2))cast(h,1);}
 if(h.id===4&&h.cd[1]<=0&&h.mana>=22&&mates.some(a=>a.hp/a.maxHp<.55&&a.pos.distanceTo(h.pos)<10))cast(h,1);}
function update(dt){game.time+=dt;game.wave-=dt;for(const k in game.utility)game.utility[k]=Math.max(0,game.utility[k]-dt);if(game.wave<=0){spawnWave();game.wave=12}aiShop(dt);for(const h of game.heroes){h.mixer.update(dt);for(let i=0;i<4;i++)h.cd[i]=Math.max(0,h.cd[i]-dt);h.shield=Math.max(0,h.shield-dt);h.buff=Math.max(0,h.buff-dt);h.invis=Math.max(0,h.invis-dt);h.mana=Math.min(100,h.mana+7*dt);if(!h.dead&&h.pos.distanceTo(h.spawn)<7.5&&h.hp<h.maxHp){h.hp=Math.min(h.maxHp,h.hp+h.maxHp*.22*dt);h.mana=100;updateBar(h)}h.goldT+=dt;if(h.goldT>=1){h.goldT-=1;h.gold+=2;if(h.player)updateGold()}if(h.invis<=0&&h.model.children.length&&h.root.visible&&!h._opaque){h.root.traverse(o=>{if(o.material){o.material.opacity=1;o.material.transparent=false}});h._opaque=true}if(h.dead){h.respawn-=dt;if(h.respawn<=0){h.dead=false;h.hp=h.maxHp;h.mana=100;h.pos.copy(h.spawn);h.root.visible=true;h._opaque=false;h.retreat=false;h._stillT=0;h._lastPos=null;h.anim='';setAnim(h,'idle');updateBar(h)}continue}h.player?movePlayer(h,dt):aiHero(h,dt)}
 for(const m of game.minions){if(m.dead)continue;m.cd-=dt;if(m.gear){m.walk+=dt*9;m.gear.position.y=Math.abs(Math.sin(m.walk))*.08;m.gear.rotation.z=Math.sin(m.walk)*.06}let[t,d]=nearest(m);if(t&&d<m.range){if(m.cd<=0){m.cd=1.05;m.range>2?minionShot(m,t):hurt(m,t,m.atk)}}else{m.pos.x+=(m.team?-1:1)*m.speed*dt;m.root.rotation.y=m.team?-Math.PI/2:Math.PI/2}}
 for(const s of game.structures){if(s.dead)continue;s.cd-=dt;if(s.root.userData.gem)s.root.userData.gem.rotation.y+=dt;let[t,d]=nearest(s,enemies(s).filter(e=>e.kind!=='tower'&&e.kind!=='core'));if(t&&d<s.range&&s.cd<=0){s.cd=1;projectile(s,t,s.atk,s.team?0xff4868:0x42d6ff,20)}}
 for(const q of game.shots){if(q.target.dead){q.dead=true;continue}let v=q.target.pos.clone().add(new THREE.Vector3(0,.8,0)).sub(q.pos),d=v.length();if(d<.45){hurt(q.src,q.target,q.dmg);fxSprite(q.pos.clone(),q.color||0xffffff,1.3,.15,null,{shrink:-2});q.dead=true;scene.remove(q.mesh)}else{q.pos.addScaledVector(v.normalize(),q.speed*dt);q._t=(q._t||0)+dt;if(q._t>.03){q._t=0;fxSprite(q.pos.clone(),q.color||0xffffff,.5,.26,null,{shrink:2.6})}}}game.shots=game.shots.filter(q=>!q.dead);
 for(const z of game.zones){z.life-=dt;if(z.windup>0){z.windup-=dt;let k=clamp(1-z.windup/.5,.02,1);z.mesh.scale.setScalar(k*z.r/.1);z.warn.material.opacity=.5+.4*Math.sin(game.time*18);if(z.windup<=0){scene.remove(z.warn);z.warn=null;ring(z.pos,z.color,z.r)}}else{z.tick-=dt;z.mesh.material.opacity=.16+.09*Math.sin(game.time*7);if(z.tick<=0){z.tick=.45;all().filter(e=>e.team!==z.team&&!e.dead&&e.pos.distanceTo(z.pos)<z.r).forEach(e=>hurt(null,e,z.dmg))}}if(z.life<=0){scene.remove(z.mesh);if(z.warn)scene.remove(z.warn);scorch(z.pos,z.r*.8)}}game.zones=game.zones.filter(z=>z.life>0);
 for(const e of game.effects){e.life-=dt;if(e.vel){e.mesh.position.addScaledVector(e.vel,dt);if(e.grav)e.vel.y+=e.grav*dt}if(e.vy)e.mesh.position.y+=e.vy*dt;if(e.grow)e.mesh.scale.multiplyScalar(1+e.grow*dt);if(e.shrink)e.mesh.scale.multiplyScalar(Math.max(.001,1-e.shrink*dt));if(e.mesh.material)e.mesh.material.opacity=(e.fadeFrom!==undefined?e.fadeFrom:1)*clamp(e.maxLife?e.life/e.maxLife:e.life*2,0,1);if(e.life<=0)scene.remove(e.mesh)}game.effects=game.effects.filter(e=>e.life>0);game.minions=game.minions.filter(m=>{if(m.dead||Math.abs(m.pos.x)>62){scene.remove(m.root);return false}return true});followCamera(dt);updateHUD()}
function minionShot(m,t){projectile(m,t,m.atk,m.team?0xff5874:0x50d6ff,15)}
function followCamera(dt){let p=game.player,desired=p.pos.clone().add(new THREE.Vector3(-8.2,14.5,12.6));camera.position.lerp(desired,1-Math.pow(.001,dt));if(game.shake>0){game.shake=Math.max(0,game.shake-dt*2.4);let sk=game.shake*.32;camera.position.x+=rand(-sk,sk);camera.position.y+=rand(-sk,sk);camera.position.z+=rand(-sk,sk)}camera.lookAt(p.pos.x+2.2,p.pos.y+.55,p.pos.z)}
function updateHUD(){let p=game.player;let db=$('#deadBox');if(db){db.style.display=p.dead?'block':'none';if(p.dead)db.innerHTML='已阵亡<br><b>'+Math.ceil(p.respawn)+'</b><small>秒后复活</small>'}$('#heroName').textContent=p.def.name+' · '+p.def.role;$('#level').textContent='  Lv.'+p.level;$('#hp').style.width=100*p.hp/p.maxHp+'%';$('#mp').style.width=p.mana+'%';$('#xp').style.width=100*p.xp/(p.level*120)+'%';$('#bk').textContent=game.blueKills;$('#rk').textContent=game.redKills;let s=Math.floor(game.time);$('#time').textContent=String(s/60|0).padStart(2,'0')+':'+String(s%60).padStart(2,'0');p.def.skills.forEach((n,i)=>$('#sk'+i).textContent=n);let _lh=document.querySelector('.skill.lasthit');if(_lh){let m=pickTarget(p,'lasthit');_lh.classList.toggle('ready',!!(m&&m.hp<=p.atk))}let _tw=document.querySelector('.skill.tower');if(_tw)_tw.classList.toggle('ready',!!pickTarget(p,'tower'));document.querySelectorAll('.skill').forEach(b=>{let s=b.dataset.s,cd=(s==='a'||s==='lh'||s==='tw')?p.cd[3]:p.cd[+s],o=b.querySelector('.cd');o.style.display=cd>0?'flex':'none';o.textContent=cd>0?cd.toFixed(cd<3?1:0):''});document.querySelectorAll('.util').forEach(b=>{let cd=game.utility[b.dataset.u],o=b.querySelector('.cd');o.style.display=cd>0?'flex':'none';o.textContent=cd>0?Math.ceil(cd):''});drawMap()}
function drawMap(){let c=$('#map'),x=c.getContext('2d'),w=c.width=c.clientWidth*2,h=c.height=c.clientHeight*2;x.clearRect(0,0,w,h);x.fillStyle='#163726';x.fillRect(0,0,w,h);x.fillStyle='#5e6267';x.fillRect(0,h*.39,w,h*.22);x.fillStyle='#1c6980';x.fillRect(w*.475,0,w*.05,h);for(const e of all()){if(e.dead)continue;x.fillStyle=e.team?'#ff536f':'#4bd8ff';let px=(e.pos.x+65)/130*w,pz=(e.pos.z+33)/66*h,r=e.kind==='hero'?5:e.kind==='core'?6:3;x.beginPath();x.arc(px,pz,r,0,7);x.fill()}}
function floatText(pos,text,color){let v=pos.clone().add(new THREE.Vector3(0,2.5,0)).project(camera),d=document.createElement('div');d.className='damage';d.style.color='#'+color.toString(16).padStart(6,'0');d.style.left=(v.x*.5+.5)*innerWidth+'px';d.style.top=(-v.y*.5+.5)*innerHeight+'px';d.textContent=text;document.body.appendChild(d);setTimeout(()=>d.remove(),760)}
function feed(text,color=0xffffff){let d=document.createElement('div');d.className='feed';d.style.color='#'+color.toString(16).padStart(6,'0');d.textContent=text;$('#feed').prepend(d);setTimeout(()=>d.remove(),5200)}
function finish(blue){if(game.over)return;game.over=true;$('#hud').classList.add('hidden');$('#end').classList.remove('hidden');$('#result').textContent=blue?'赤晶破碎 · 苍穹胜利':'苍穹陷落 · 赤渊胜利';$('#result').style.color=blue?'#55d8ff':'#ff5d7b';let p=game.player;$('#stats').textContent=`${p.def.name}　击败 ${p.kills}　阵亡 ${p.deaths}　等级 ${p.level}`}
function loop(){if(!game||game.over)return;let _rdt=Math.min(.05,clock.getDelta()),dt=_rdt;if(game.slow>0){game.slow-=_rdt;dt=_rdt*.22}if(waterTex)waterTex.offset.y-=dt*.12;fpsFrames++;fpsTime+=dt;if(fpsTime>=.5){$('#fps').textContent=Math.round(fpsFrames/fpsTime);fpsFrames=0;fpsTime=0}update(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}

addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(!game)return;let p=game.player,k=e.key.toLowerCase();if(k==='j')basic(p);if(k==='k')cast(p,0);if(k==='l')cast(p,1);if(k==='u')cast(p,2);if(k==='r')useUtility('recall');if(k==='f')useUtility('heal');if(k==='g')useUtility('flash');if(k==='b')toggleShop();if(k==='h')basic(p,'lasthit');if(k==='t')basic(p,'tower')});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
const j=$('#joy'),kn=$('#knob');function moveJoy(e){let t=[...e.changedTouches].find(q=>joy.id===null||q.identifier===joy.id);if(!t)return;if(joy.id===null)joy.id=t.identifier;let r=j.getBoundingClientRect(),dx=t.clientX-r.left-r.width/2,dy=t.clientY-r.top-r.height/2,l=Math.hypot(dx,dy),m=r.width*.35;if(l>m){dx*=m/l;dy*=m/l}joy.x=dx/m;joy.y=dy/m;kn.style.transform=`translate(${dx}px,${dy}px)`}j.addEventListener('touchstart',e=>{e.preventDefault();moveJoy(e)},{passive:false});j.addEventListener('touchmove',e=>{e.preventDefault();moveJoy(e)},{passive:false});j.addEventListener('touchend',e=>{if([...e.changedTouches].some(t=>t.identifier===joy.id)){joy.x=joy.y=0;joy.id=null;kn.style.transform=''}},{passive:false});document.querySelectorAll('.skill').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();if(!game)return;let s=b.dataset.s;if(s==='a')basic(game.player);else if(s==='lh')basic(game.player,'lasthit');else if(s==='tw')basic(game.player,'tower');else cast(game.player,+s)}));
document.querySelectorAll('.util').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();useUtility(b.dataset.u)}));
function rand(a,b){return a+Math.random()*(b-a)}


/* ===== 军备商店:金币经济与六件装备 ===== */
const ITEMS=[
 {id:0,icon:'⚔️',name:'破军之刃',cost:1200,desc:'+45 攻击',apply:h=>h.atk+=45},
 {id:1,icon:'🛡️',name:'不动明王甲',cost:1100,desc:'+18%减伤 +250生命',apply:h=>{h.armor+=.18;h.maxHp+=250;h.hp+=250;updateBar(h)}},
 {id:2,icon:'💚',name:'巨人腰带',cost:1000,desc:'+480 生命',apply:h=>{h.maxHp+=480;h.hp+=480;updateBar(h)}},
 {id:3,icon:'👟',name:'疾风之靴',cost:700,desc:'+1.3 移速',apply:h=>h.speed+=1.3},
 {id:4,icon:'🩸',name:'噬血镰',cost:1300,desc:'+25攻击 +15%吸血',apply:h=>{h.atk+=25;h.lifesteal+=.15}},
 {id:5,icon:'📖',name:'贤者法典',cost:1250,desc:'+30攻击 技能冷却-20%',apply:h=>{h.atk+=30;h.cdr=Math.min(.4,(h.cdr||0)+.2)}}
];
function gold(h,n){if(!h||h.kind!=='hero')return;h.gold+=n;if(h.player)updateGold()}
function updateGold(){let el=$('#goldNum');if(el&&game&&game.player)el.textContent=Math.floor(game.player.gold)}
function toggleShop(){let p=$('#shopPanel');if(p)p.classList.toggle('open')}
function buyItem(i){let p=game&&game.player;if(!p||p.dead||game.over)return;let it=ITEMS[i];if(p.items.includes(i)){feed('已拥有 '+it.name,0xffb45c);return}if(p.gold<it.cost){feed('金币不足，还差 '+Math.ceil(it.cost-p.gold),0xff7a7a);return}p.gold-=it.cost;p.items.push(i);it.apply(p);let el=$('#item'+i);if(el)el.classList.add('owned');updateGold();ring(p.pos,0xffd45c,1.6);feed(`${p.def.name} 购入 ${it.name}`,0xffd45c)}
function aiShop(dt){game._shopT=(game._shopT||0)+dt;if(game._shopT<4)return;game._shopT=0;for(const h of game.heroes){if(h.player||h.dead)continue;let pick=ITEMS.filter(it=>!h.items.includes(it.id)&&h.gold>=it.cost).sort((a,b)=>a.cost-b.cost)[0];if(pick){h.gold-=pick.cost;h.items.push(pick.id);pick.apply(h)}}}
function initShopUI(){if($('#shopPanel'))return;
 let st=document.createElement('style');st.textContent=`
.skill.lasthit{border-color:#ffd45c;background:radial-gradient(circle at 36% 27%,#8a6a1e,#241a05 72%);font-size:17px}
.skill.tower{border-color:#9ad0ff;background:radial-gradient(circle at 36% 27%,#2a5f8a,#0a1c2c 72%);font-size:17px}
.skill.ready{box-shadow:0 0 16px #ffd45ccc,inset 0 0 12px #ffd45c66;filter:brightness(1.25)}
#deadBox{position:fixed;top:38%;left:50%;transform:translateX(-50%);background:rgba(10,4,8,.82);border:1px solid rgba(255,90,120,.45);color:#ff9fb2;padding:14px 30px;border-radius:12px;font:600 15px/1.5 sans-serif;text-align:center;z-index:35;display:none;pointer-events:none}
#deadBox b{display:block;font-size:38px;color:#fff;line-height:1.1}#deadBox small{font-size:11px;color:#c98a99}
#goldBox{position:fixed;top:64px;right:12px;background:rgba(8,16,24,.8);border:1px solid rgba(255,212,92,.4);color:#ffd45c;padding:6px 12px;border-radius:20px;font:600 14px/1 sans-serif;z-index:30}
#shopBtn{position:fixed;top:102px;right:12px;width:44px;height:44px;border-radius:50%;border:1px solid rgba(255,212,92,.5);background:rgba(8,16,24,.85);font-size:20px;z-index:30;color:#ffd45c;cursor:pointer}
#shopPanel{position:fixed;inset:0;margin:auto;width:min(92vw,420px);height:fit-content;max-height:78vh;overflow:auto;background:rgba(7,14,22,.96);border:1px solid rgba(255,212,92,.35);border-radius:14px;padding:16px;z-index:40;display:none;color:#dfe9f2;font-family:sans-serif}
#shopPanel.open{display:block}
#shopPanel h3{margin:0 0 10px;color:#ffd45c;font-size:16px;display:flex;align-items:center}
#shopPanel h3 small{font-weight:400;color:#8fa4b8;font-size:11px;margin-left:8px;flex:1}
#shopClose{background:none;border:none;color:#8fa4b8;font-size:18px;cursor:pointer}
.shopItem{display:flex;align-items:center;gap:10px;width:100%;margin-bottom:8px;padding:10px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.12);border-radius:10px;color:#dfe9f2;cursor:pointer;text-align:left;font-family:inherit}
.shopItem .ico{font-size:22px}.shopItem .inf{flex:1;display:flex;flex-direction:column;gap:2px}.shopItem .inf i{font-style:normal;font-size:11px;color:#8fa4b8}
.shopItem em{font-style:normal;color:#ffd45c;font-weight:700;font-size:13px}
.shopItem.owned{opacity:.45}.shopItem.owned em{color:#7fca7f}.shopItem.owned em::after{content:" ✓"}`;document.head.appendChild(st);
 let dbx=document.createElement('div');dbx.id='deadBox';document.body.appendChild(dbx);let gb=document.createElement('div');gb.id='goldBox';gb.innerHTML='🪙 <b id="goldNum">0</b>';document.body.appendChild(gb);
 let btn=document.createElement('button');btn.id='shopBtn';btn.textContent='🛒';btn.addEventListener('pointerdown',e=>{e.preventDefault();toggleShop()});document.body.appendChild(btn);
 let panel=document.createElement('div');panel.id='shopPanel';panel.innerHTML='<h3>⚖️ 军备商店 <small>补刀+38 · 击杀+300 · 每秒+2 (电脑按B开关)</small><button id="shopClose">✕</button></h3><div id="shopItems"></div>';document.body.appendChild(panel);
 panel.querySelector('#shopClose').addEventListener('click',toggleShop);
 let box=panel.querySelector('#shopItems');ITEMS.forEach(it=>{let b=document.createElement('button');b.className='shopItem';b.id='item'+it.id;b.innerHTML=`<span class="ico">${it.icon}</span><span class="inf"><b>${it.name}</b><i>${it.desc}</i></span><em>🪙${it.cost}</em>`;b.addEventListener('click',()=>buyItem(it.id));box.appendChild(b)})}
