import * as THREE from '../vendor/three.module.js';
import {GLTFLoader} from '../vendor/GLTFLoader.js';

const DATA=[
 {name:'朔月 · 白曜',role:'月刃战士 / 东方近战',color:0xff4f68,model:0,desc:'白发、玄甲与赤金分层长袍。双月轮采用独立金属结构，攻击时切换近战骨骼动画。',kind:'moon'},
 {name:'紫序 · 零',role:'幻术师 / 未来法师',color:0xa662ff,model:1,desc:'黑紫复合战甲、发光导能纹路与悬浮符牌。施法动作会驱动全身骨骼动画。',kind:'cyber'}
];
const ACTIONS=[['待机','idle'],['奔跑','sprint'],['普攻','attack-melee-right'],['施法','holding-both-shoot'],['受击','emote-no'],['死亡','die']];
const $=s=>document.querySelector(s),stage=$('#stage'),loading=$('#loading');
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;stage.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x070b12);scene.fog=new THREE.Fog(0x070b12,11,26);const camera=new THREE.PerspectiveCamera(31,innerWidth/innerHeight,.1,60);camera.position.set(0,3.2,9);
scene.add(new THREE.HemisphereLight(0xa8d8ff,0x27161d,1.65));const key=new THREE.DirectionalLight(0xffe4d2,4.6);key.position.set(5,9,6);key.castShadow=true;key.shadow.mapSize.set(1536,1536);key.shadow.camera.left=-5;key.shadow.camera.right=5;key.shadow.camera.top=7;key.shadow.camera.bottom=-2;scene.add(key);const rim=new THREE.DirectionalLight(0x776cff,4);rim.position.set(-5,5,-5);scene.add(rim);

// 科幻展厅：真正的3D墙板、灯箱和展示台。
const wallMat=new THREE.MeshStandardMaterial({color:0x111927,metalness:.55,roughness:.35});const darkMat=new THREE.MeshStandardMaterial({color:0x080d15,metalness:.7,roughness:.28});
function box(w,h,d,m,x,y,z,rx=0,ry=0,rz=0,parent=scene){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.rotation.set(rx,ry,rz);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
box(15,8,.4,wallMat,0,3,-4);for(let x=-6;x<=6;x+=3)box(.08,7,.15,darkMat,x,3.2,-3.75);for(let y=.8;y<6;y+=1.6)box(14,.06,.15,darkMat,0,y,-3.74);
const whiteGlow=new THREE.MeshStandardMaterial({color:0xd8f1ff,emissive:0x7dcfff,emissiveIntensity:2.5,roughness:.25});box(4.8,1.25,.12,whiteGlow,0,3.55,-3.5);box(2.6,.18,.12,whiteGlow,-4.6,4.9,-3.5);box(2.6,.18,.12,new THREE.MeshStandardMaterial({color:0xffb0ae,emissive:0xff425f,emissiveIntensity:2}),4.6,4.9,-3.5);
const floor=box(18,.3,16,new THREE.MeshStandardMaterial({color:0x151d27,metalness:.55,roughness:.3}),0,-.28,1);const platform=new THREE.Mesh(new THREE.CylinderGeometry(3.25,3.55,.38,8),new THREE.MeshStandardMaterial({color:0x202b39,metalness:.8,roughness:.22}));platform.position.y=-.03;platform.receiveShadow=true;scene.add(platform);const ring=new THREE.Mesh(new THREE.TorusGeometry(2.72,.045,8,80),new THREE.MeshStandardMaterial({color:0xff4f68,emissive:0xff4f68,emissiveIntensity:3}));ring.rotation.x=Math.PI/2;ring.position.y=.18;scene.add(ring);

const material=(color,{metal=.25,rough=.38,glow=false,side=THREE.FrontSide}={})=>new THREE.MeshStandardMaterial({color,metalness:metal,roughness:rough,emissive:glow?color:0,emissiveIntensity:glow?2.4:0,side});
function add(parent,geo,mat,pos=[0,0,0],rot=[0,0,0],scale=[1,1,1]){const m=new THREE.Mesh(geo,mat);m.position.set(...pos);m.rotation.set(...rot);m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function panel(top,bottom,height,depth=.045){const x1=top/2,x2=bottom/2,y=height;const p=[-x1,y/2,depth,x1,y/2,depth,-x2,-y/2,depth,x2,-y/2,depth,-x1,y/2,-depth,x1,y/2,-depth,-x2,-y/2,-depth,x2,-y/2,-depth];const idx=[0,2,1,1,2,3,4,5,6,5,7,6,0,1,4,1,5,4,2,6,3,3,6,7,0,4,2,2,4,6,1,3,5,3,7,5];const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setIndex(idx);g.computeVertexNormals();return g}
function tube(points,r=.025,segments=20){return new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p))),segments,r,7,false)}
function torusBlade(parent,x,y,z,flip,main,gold,glow){const g=new THREE.Group();g.position.set(x,y,z);g.rotation.y=flip?Math.PI:0;parent.add(g);add(g,new THREE.TorusGeometry(.39,.065,8,36,Math.PI*1.55),main,[0,0,0],[0,0,.7]);add(g,new THREE.TorusGeometry(.27,.022,6,28,Math.PI*1.55),glow,[0,0,0],[0,0,.7]);for(let i=0;i<4;i++){const a=.7+i*.4;add(g,new THREE.ConeGeometry(.075,.22,5),gold,[Math.cos(a)*.4,Math.sin(a)*.4,0],[0,0,a-Math.PI/2]);}add(g,new THREE.CylinderGeometry(.055,.055,.32,10),gold,[0,-.12,0],[0,0,.8]);return g}
function moonGear(root){const red=material(0x8b152b,{rough:.42}),black=material(0x12151d,{metal:.45,rough:.3}),gold=material(0xd9a858,{metal:.85,rough:.2}),white=material(0xe9edf2,{rough:.58}),glow=material(0xff4f68,{glow:true});
 // 白色长发：多束曲线形成背部轮廓。
 for(let i=0;i<13;i++){const a=(i-6)*.08;const len=1.05-Math.abs(i-6)*.035;add(root,tube([[a*.65,1.93,-.06],[a,1.55,-.18],[a*1.5,2-len,-.08]],.035+(i%3)*.006,22),white)}
 add(root,new THREE.SphereGeometry(.205,20,14),white,[0,1.86,-.02],[0,0,0],[1.12,.78,1.05]);for(let i=0;i<5;i++)add(root,new THREE.ConeGeometry(.035,.24,7),gold,[(i-2)*.06,2.09,-.02],[0,0,(i-2)*.13]);
 // 分层长袍与金色滚边。
 add(root,panel(.48,.95,1.25),red,[0,.68,.04],[0,0,0]);add(root,panel(.36,.73,1.16),black,[-.34,.72,-.03],[0,.28,.06]);add(root,panel(.36,.73,1.16),black,[.34,.72,-.03],[0,-.28,-.06]);add(root,panel(.035,.07,1.18),gold,[0,.7,.095]);
 add(root,new THREE.TorusGeometry(.32,.045,8,28),gold,[0,1.13,0],[Math.PI/2,0,0],[1.25,1,1]);[-1,1].forEach(s=>{add(root,new THREE.BoxGeometry(.4,.18,.28),black,[s*.34,1.51,0],[0,0,s*.08]);add(root,new THREE.ConeGeometry(.12,.34,5),gold,[s*.55,1.48,0],[0,0,-s*Math.PI/2]);add(root,new THREE.CylinderGeometry(.12,.14,.32,10),red,[s*.42,.93,.04],[0,0,s*.12]);});
 torusBlade(root,-.62,.83,.15,false,black,gold,glow);torusBlade(root,.62,.83,.15,true,black,gold,glow);add(root,new THREE.TorusGeometry(.55,.025,7,50),glow,[0,.16,0],[Math.PI/2,0,0]);
 root.userData.floaters=[];for(let i=0;i<8;i++){const f=add(root,new THREE.OctahedronGeometry(.025,0),glow,[Math.sin(i)*.75,.35+(i%4)*.38,Math.cos(i)*.35]);f.userData.phase=i*.8;root.userData.floaters.push(f)}
}
function cyberGear(root){const armor=material(0x171c2c,{metal:.82,rough:.22}),plate=material(0x32394d,{metal:.75,rough:.2}),purple=material(0xa662ff,{glow:true}),skin=material(0xd9a68f,{rough:.65}),black=material(0x06080f,{metal:.4,rough:.35});
 // 胸、肩、腿部装甲板。
 add(root,panel(.42,.31,.55,.09),armor,[0,1.36,.08]);add(root,panel(.29,.38,.32,.1),plate,[0,1.08,.09]);[-1,1].forEach(s=>{add(root,new THREE.BoxGeometry(.38,.16,.3),plate,[s*.36,1.51,0],[0,0,s*.14]);add(root,new THREE.CylinderGeometry(.115,.13,.38,8),armor,[s*.41,.93,.02],[0,0,s*.08]);add(root,panel(.2,.14,.52,.07),armor,[s*.19,.48,.08],[0,0,-s*.08]);add(root,new THREE.BoxGeometry(.2,.33,.23),plate,[s*.18,.16,.03]);});
 // 面罩、科技发型与发光导能线。
 add(root,new THREE.SphereGeometry(.19,18,12),skin,[0,1.83,.01],[0,0,0],[1,.92,.92]);add(root,new THREE.BoxGeometry(.34,.075,.075),purple,[0,1.87,.18]);for(let i=0;i<8;i++){const a=(i-3.5)*.16;add(root,new THREE.ConeGeometry(.045,.38,7),black,[a*.15,2.04,-.02],[.2,0,-a]);}
 add(root,new THREE.BoxGeometry(.035,.48,.025),purple,[0,1.34,.19]);[-1,1].forEach(s=>{add(root,new THREE.BoxGeometry(.025,.36,.025),purple,[s*.22,1.35,.18],[0,0,-s*.28]);add(root,new THREE.BoxGeometry(.025,.31,.025),purple,[s*.18,.48,.17],[0,0,s*.08]);});
 // 悬浮符牌。
 root.userData.cards=[];for(let i=0;i<7;i++){const a=-1.05+i*.35;const c=new THREE.Group();c.position.set(Math.cos(a)*1.05,.95+i*.08,-.05+Math.sin(a)*.34);c.rotation.set(.1,a*.3,-a*.2);root.add(c);add(c,new THREE.BoxGeometry(.25,.38,.018),material(i%2?0x42216b:0x1e395f,{metal:.35,rough:.25}),[0,0,0]);add(c,new THREE.TorusGeometry(.065,.012,5,16),purple,[0,.03,.018]);add(c,new THREE.BoxGeometry(.12,.018,.018),purple,[0,-.09,.018]);c.userData.phase=i*.72;root.userData.cards.push(c)}
 add(root,new THREE.TorusGeometry(.58,.035,7,48),purple,[0,.14,0],[Math.PI/2,0,0]);root.userData.floaters=[];
}

const loader=new GLTFLoader(),heroes=[],mixers=[],clips=[],currentActions=[];let selected=0,root=null,yaw=.3,targetYaw=.3,targetPitch=0,pitch=0,zoom=8.5,targetZoom=8.5,drag=false,lx=0,ly=0,pinch=0;
function recolorBase(model,d){model.traverse(o=>{if(!o.isMesh)return;const head=/head/i.test(o.name);o.material=material(head?0xd5a68f:(d.kind==='moon'?0x18151b:0x111522),{metal:head?0:.18,rough:head?.7:.42});o.castShadow=true;o.receiveShadow=true;});}
function loadHero(d,i){return new Promise((resolve,reject)=>loader.load(`../models/hero-${d.model}.glb`,g=>{const wrap=new THREE.Group(),model=g.scene;model.scale.setScalar(3.15);const b=new THREE.Box3().setFromObject(model),center=b.getCenter(new THREE.Vector3());model.position.set(-center.x,-b.min.y,-center.z);recolorBase(model,d);wrap.add(model);d.kind==='moon'?moonGear(wrap):cyberGear(wrap);wrap.userData.model=model;heroes[i]=wrap;mixers[i]=new THREE.AnimationMixer(model);clips[i]=g.animations;resolve()},undefined,reject))}
function play(name){const mx=mixers[selected],arr=clips[selected];if(!mx||!arr)return;const clip=arr.find(a=>a.name===name)||arr.find(a=>a.name.includes(name))||arr[0];const next=mx.clipAction(clip);if(currentActions[selected]!==next){currentActions[selected]?.fadeOut(.18);next.reset().fadeIn(.18).play();next.clampWhenFinished=name==='die';next.setLoop(name==='die'?THREE.LoopOnce:THREE.LoopRepeat);currentActions[selected]=next}document.querySelectorAll('#actions button').forEach((b,i)=>b.classList.toggle('active',ACTIONS[i][1]===name))}
function select(i){if(root)scene.remove(root);selected=i;root=heroes[i];scene.add(root);root.rotation.y=yaw;const d=DATA[i],hex=`#${d.color.toString(16).padStart(6,'0')}`;document.documentElement.style.setProperty('--accent',hex);ring.material.color.setHex(d.color);ring.material.emissive.setHex(d.color);rim.color.setHex(d.color);$('#name').textContent=d.name;$('#role').textContent=d.role;$('#desc').textContent=d.desc;document.querySelectorAll('.hero-btn').forEach((b,n)=>b.classList.toggle('active',n===i));play('idle')}
DATA.forEach((d,i)=>{const b=document.createElement('button');b.className='hero-btn';b.style.setProperty('--c',`#${d.color.toString(16).padStart(6,'0')}`);b.innerHTML=i?'◈ 未来<br>紫序 · 零':'☾ 东方<br>朔月 · 白曜';b.onclick=()=>select(i);$('#switcher').append(b)});ACTIONS.forEach(([label,name])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>play(name);$('#actions').append(b)});
Promise.all(DATA.map(loadHero)).then(()=>{select(0);loading.classList.add('hide')}).catch(e=>{console.error(e);loading.textContent='模型加载失败，请刷新重试'});
renderer.domElement.addEventListener('pointerdown',e=>{drag=true;lx=e.clientX;ly=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;targetYaw+=(e.clientX-lx)*.012;targetPitch=Math.max(-.3,Math.min(.28,targetPitch+(e.clientY-ly)*.004));lx=e.clientX;ly=e.clientY});renderer.domElement.addEventListener('pointerup',()=>drag=false);renderer.domElement.addEventListener('wheel',e=>{targetZoom=Math.max(6.2,Math.min(11,targetZoom+e.deltaY*.006));e.preventDefault()},{passive:false});renderer.domElement.addEventListener('touchmove',e=>{if(e.touches.length===2){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch)targetZoom=Math.max(6.2,Math.min(11,targetZoom+(pinch-d)*.018));pinch=d}},{passive:false});renderer.domElement.addEventListener('touchend',()=>pinch=0);
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);mixers.forEach(m=>m?.update(dt));yaw+=(targetYaw-yaw)*.09;pitch+=(targetPitch-pitch)*.09;zoom+=(targetZoom-zoom)*.09;if(root){root.rotation.y=yaw;root.userData.cards?.forEach(c=>{c.position.y+=Math.sin(performance.now()*.002+c.userData.phase)*.0008;c.rotation.y+=dt*.45});root.userData.floaters?.forEach(f=>{f.position.y+=Math.sin(performance.now()*.002+f.userData.phase)*.0005})}camera.position.set(0,3.05+pitch*3,zoom);camera.lookAt(0,1.18,0);renderer.render(scene,camera)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
